[package]
name = "throttled_xrp_rpc"
version = "0.1.0"
authors = ["Aiden McClelland <aiden.k.mcclelland@gmail.com>", "Drew Ansbacher <drew.ansbacher@gmail.com>"]
repository = "https://github.com/DR-BoneZ/throttled-xrp-rpc-rs"
homepage = "https://github.com/DR-BoneZ/throttled-xrp-rpc-rs"
license = "MIT"
readme = "README.md"
documentation = "http://docs.rs/throttled_xrp_rpc/"
description = "Throttled XRP RPC API client for Rust."
edition = "2018"


[dependencies]
throttled_json_rpc = "0.0.1"
failure = "0.1.5"
reqwest = "0.9.18"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"
bigdecimal = { version = "0.1.0", features = ["serde"] }